### ISSUE TITLE
Locale translation

### ISSUE THREAD

**Issue by headquarter8302** [Wikitubia/wikitubia.github.io#13]
It is for our interest to translate the site to popular locales (es, fr, hi). These will be separated into directories like so:
```
/en/index.html
/fr/index.html
/hi/index.html
```
All changes will be tracked in the Site translation project and this issue. Resources aren't translated unless needed (e.g. images, arbitrary text, etc.), so they would point to the root `/res/` directory.

Contributors and translators are welcome.

**Comment by Saurmandal** [comment]
Are you going add a lang switcher after more locales are added?

**Comment by headquarter8302** [comment]
Yes, there will be a script checking the user's preferred locale, then asks the user to navigate to their preferred locale

**Comment by headquarter8302** [comment]
This is dead in the water isn't it.

Might need to poke Leafy again

**Comment by Saurmandal** [comment]
> This is dead in the water isn't it.
> 
> Might need to poke Leafy again
Yes sadly 🗿

**Comment by headquarter8302** [comment]
*sigh*
